[package]
name = "supervisor-example"
version = "0.1.0"
edition = "2021"

[dependencies]
spawned-rt = { workspace = true }
spawned-concurrency = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "supervisor-example"
path = "main.rs"
