[package]
name = "showcase"
version = "0.1.0"
edition = "2021"

[dependencies]
spawned-rt = { path = "../../rt" }
spawned-concurrency = { path = "../../concurrency" }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
