[package]
name = "busy_actor_warning"
version = "0.1.0"
edition = "2024"

[dependencies]
spawned-rt = { workspace = true }
spawned-concurrency = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "busy_actor_warning"
path = "main.rs"
