[package]
name = "signal_test_threads"
version = "0.1.0"
edition = "2021"

[dependencies]
spawned-concurrency = { path = "../../concurrency" }
spawned-rt = { path = "../../rt" }
tracing = { workspace = true }
